### ISSUE TITLE
小程序ar第四篇第二个例子，摄影头影像黑的。

### ISSUE THREAD

**Issue by ironman1987** [Starsky-Synlitec/CnBlog#1]
小程序ar第四篇第二个例子，摄影头影像黑的。
手机：iphone8 plus
微信版本：7.0.8

**Comment by Starsky-Synlitec** [comment]
您好，感谢您的反馈。目前我手头上还没有IOS的手机。所以不太好测试。我给您发了邮件，如果有时间您可以看一下，也帮忙一起排查一下原因。我估计可能的原因是摄像头权限相关的问题。
等我这边有了IOS的环境，再一起测试下。
再次感谢。

**Comment by ironman1987** [comment]
哇，回复神速！博客园私信无法留言，就跑到github上发issue，以为会石沉大海。
我调试了一下可以拿到摄影头数据，但是渲染的是否就没有了，我想可能是three.js datatexture与微信小程序不兼容。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Starsky-Synlitec <notifications@github.com&gt;
发送时间: 2019年11月20日 18:41
收件人: Starsky-Synlitec/CnBlog <CnBlog@noreply.github.com&gt;
抄送: How to Make Steel <664113046@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Starsky-Synlitec/CnBlog] 小程序ar第四篇第二个例子，摄影头影像黑的。 (#1)




您好，感谢您的反馈。目前我手头上还没有IOS的手机。所以不太好测试。我给您发了邮件，如果有时间您可以看一下，也帮忙一起排查一下原因。我估计可能的原因是摄像头权限相关的问题。
 等我这边有了IOS的环境，再一起测试下。
 再次感谢。

**Comment by ironman1987** [comment]
少了一句tex.needsUpdate = true;//纹理更新

**Comment by ironman1987** [comment]
问题已解决，苹果手机和安卓手机都试过了

**Comment by Starsky-Synlitec** [comment]
Great
